# Generated by Django 3.2.25 on 2024-09-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20240724_0953'),
        ('school_admin', '0006_auto_20240924_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attended', models.BooleanField(default=False)),
                ('date_attended', models.DateField(auto_now_add=True)),
                ('hall_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_ticket_student', to='school_admin.hallticketforstudent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attended', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attended_sub', to='school_admin.subjects')),
            ],
        ),
    ]
