# Generated by Django 3.2.25 on 2024-09-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0007_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='hall_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall_ticket_student', to='school_admin.hallticketforstudent'),
        ),
    ]
