# Generated by Django 3.2.25 on 2024-09-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0012_examination_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='active',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='active_status',
        ),
    ]
