# Generated by Django 3.2.25 on 2024-07-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('standard', models.IntegerField()),
                ('admin_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_admin.teacher_admin')),
            ],
        ),
    ]
