# Generated by Django 3.2.25 on 2024-07-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0002_studentteachersubjects_subjects'),
        ('student', '0002_alter_student_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_student', to='school_admin.teacher_admin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X'), (11, 'XI'), (12, 'XII')], max_length=250),
        ),
    ]
